### PR TITLE
Fix macOS wheels: drop `setuptools-scm`

### PR DESCRIPTION
**Pull request by crwood**
This PR removes the use of `setuptools-scm` in favor of declaring a hardcoded version string, effectively fixing the failing (macOS) wheel builds. Builds had been failing previously because newer versions of `setuptools-scm` can no longer be configured via `setup.py` (and must use `pyproject.toml`).

This is not ideal solution: in keeping up with recent changes in the Python packaging ecosystem, it would be preferable to shift project configuration from `setup.py` to `pyproject.toml`, _however_, this project's `setup.py` currently contains custom/milksnake-specific hooks that would presumably be need to re-implemented elsewhere (and is beyond the scope of this PR).

Note that a version string was already being hardcoded in `nix/python-challenge-bypass-ristretto.nix` (so `setuptools-scm` could not have been used to handle any/all version-string declaration anyway). I've documented this in a comment in both files; future maintainers should update the version string in both places until the entire project can be migrated to using `pyproject.toml`.

### CODE REVIEW

**Comment by hacklschorsch** [comment]
Looks good to me!

Where can I see the difference in macOS wheels not working before and now working?
I thought I had already fixed this, else I hadn't bumped the version in my earlier PR :/

**Review by hacklschorsch — APPROVED** [review]

**Comment by crwood** [comment]
>Where can I see the difference in macOS wheels not working before and now working?

I had tried building locally and got the failure shown in #58 (which you could also see [here](https://app.circleci.com/pipelines/github/PrivateStorageio/ZKAPAuthorizer/1884/workflows/b925a0a9-c312-4990-8ad0-ccc1937ba05a/jobs/8682) -- albeit under ZKAPAuthorizer).

>I thought I had already fixed this, else I hadn't bumped the version in my earlier PR :/

Oh, that's interesting. I hadn't noticed that your change passed the macOS builds independently at the time I started this (probably because it was red at the time that we merged -- but for different reasons). I'm still not sure I understand how/why `setuptools-scm` "Just Works" there and not here, but I'm glad that it does. 

Feel free to reject/close this (and, I guess, close #58?). Sorry!

**Comment by hacklschorsch** [comment]
Should we still merge this now that the wheels build fine without it?

**Comment by crwood** [comment]
Nah, let's just close it. I still don't know what led to the original breakage here but we don't gain much by trying to diagnose it (plus, a lot of adjacent things were broken at the time so it could have been related to something that is no longer a cause).

**Pull request closed without merging**
